version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/crm.db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=change-me-in-production-min-32-characters-secret-key
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/crm.db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=change-me-in-production-min-32-characters-secret-key
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - api
    command: rq worker --url redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

